function Process:_IniFileRebuild(inifilename)
	os.remove(inifilename);
	hge.Ini_SetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYUP, RESCONFIGDEFAULT_KEYUP);
	hge.Ini_SetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYDOWN, RESCONFIGDEFAULT_KEYDOWN);
	hge.Ini_SetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYLEFT, RESCONFIGDEFAULT_KEYLEFT);
	hge.Ini_SetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYRIGHT, RESCONFIGDEFAULT_KEYRIGHT);
	hge.Ini_SetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYPAUSE, RESCONFIGDEFAULT_KEYPAUSE);
	hge.Ini_SetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYSKIP, RESCONFIGDEFAULT_KEYSKIP);
	hge.Ini_SetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYENTER, RESCONFIGDEFAULT_KEYENTER);
	hge.Ini_SetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYCANCEL, RESCONFIGDEFAULT_KEYCANCEL);
	hge.Ini_SetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYESCAPE, RESCONFIGDEFAULT_KEYESCAPE);
	hge.Ini_SetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYCAPTURE, RESCONFIGDEFAULT_KEYCAPTURE);
	
	hge.Ini_SetInt(RESCONFIGS_JOYSETTING, RESCONFIGN_JOYPAUSE, RESCONFIGDEFAULT_JOYPAUSE);
	hge.Ini_SetInt(RESCONFIGS_JOYSETTING, RESCONFIGN_JOYENTER, RESCONFIGDEFAULT_JOYENTER);
	hge.Ini_SetInt(RESCONFIGS_JOYSETTING, RESCONFIGN_JOYCANCEL, RESCONFIGDEFAULT_JOYCANCEL);

	hge.Ini_SetInt(RESCONFIGS_VOLUME, RESCONFIGN_VOLMUSIC, RESCONFIGDEFAULT_VOLMUSIC);
	hge.Ini_SetInt(RESCONFIGS_VOLUME, RESCONFIGN_VOLSE, RESCONFIGDEFAULT_VOLSE);

	hge.Ini_SetInt(RESCONFIGS_CUSTOM, RESCONFIGN_SCREENMODE, RESCONFIGDEFAULT_SCREENMODE);
	hge.Ini_SetString(RESCONFIGS_CUSTOM, RESCONFIGN_USERNAME, RESCONFIGDEFAULT_USERNAME);
	hge.Ini_SetInt(RESCONFIGS_CUSTOM, RESCONFIGN_RENDERSKIP, RESCONFIGDEFAULT_RENDERSKIP);

	hge.Ini_SetInt(RESCONFIGS_CUSTOMWINDOW, RESCONFIGN_DEFAULTWINDOW, RESCONFIGDEFAULT_DEFAULTWINDOW);
	hge.Ini_SetInt(RESCONFIGS_CUSTOMWINDOW, RESCONFIGN_WINDOWLEFT, RESCONFIGDEFAULT_WINDOWLEFT);
	hge.Ini_SetInt(RESCONFIGS_CUSTOMWINDOW, RESCONFIGN_WINDOWTOP, RESCONFIGDEFAULT_WINDOWTOP);
	hge.Ini_SetInt(RESCONFIGS_CUSTOMWINDOW, RESCONFIGN_WINDOWWIDTH, RESCONFIGDEFAULT_WINDOWWIDTH);
	hge.Ini_SetInt(RESCONFIGS_CUSTOMWINDOW, RESCONFIGN_WINDOWHEIGHT, RESCONFIGDEFAULT_WINDOWHEIGHT);
	hge.Ini_SetInt(RESCONFIGS_CUSTOMWINDOW, RESCONFIGN_WINDOWTOPMOST, RESCONFIGDEFAULT_WINDOWTOPMOST);

	if __DEBUG > 0 then
		hge.Ini_SetInt(RESCONFIGS_JOYSETTING, RESCONFIGN_DEBUG_JOYSPEEDUP, RESCONFIGDEFAULT_DEBUG_JOYSPEEDUP);
	end
end

function Process:ProcessPreInitial()
	local inifilename = hge.Resource_MakePath(hge.System_GetState(HGE_INIFILE, CONFIG_STR_FILENAME));
	if io.open(inifilename, "r") == nil then
		self:_IniFileRebuild(inifilename);
	end
	self.keyUp			= hge.Ini_GetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYUP, RESCONFIGDEFAULT_KEYUP);
	self.keyDown		= hge.Ini_GetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYDOWN, RESCONFIGDEFAULT_KEYDOWN);
	self.keyLeft		= hge.Ini_GetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYLEFT, RESCONFIGDEFAULT_KEYLEFT);
	self.keyRight		= hge.Ini_GetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYRIGHT, RESCONFIGDEFAULT_KEYRIGHT);
	self.keyPause		= hge.Ini_GetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYPAUSE, RESCONFIGDEFAULT_KEYPAUSE);
	self.keySkip		= hge.Ini_GetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYSKIP, RESCONFIGDEFAULT_KEYSKIP);
	self.keyEnter		= hge.Ini_GetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYENTER, RESCONFIGDEFAULT_KEYENTER);
	self.keyCancel	= hge.Ini_GetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYCANCEL, RESCONFIGDEFAULT_KEYCANCEL);
	self.keyEscape	= hge.Ini_GetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYESCAPE, RESCONFIGDEFAULT_KEYESCAPE);
	self.keyCapture	= hge.Ini_GetInt(RESCONFIGS_KEYSETTING, RESCONFIGN_KEYCAPTURE, RESCONFIGDEFAULT_KEYCAPTURE);

	self.joyPause		= hge.Ini_GetInt(RESCONFIGS_JOYSETTING, RESCONFIGN_JOYPAUSE, RESCONFIGDEFAULT_JOYPAUSE);
	self.joyEnter		=	hge.Ini_GetInt(RESCONFIGS_JOYSETTING, RESCONFIGN_JOYENTER, RESCONFIGDEFAULT_JOYENTER);
	self.joyCancel	=	hge.Ini_GetInt(RESCONFIGS_JOYSETTING, RESCONFIGN_JOYCANCEL, RESCONFIGDEFAULT_JOYCANCEL);
	if __DEBUG > 0 then
		self.debug_joySpeedUp = hge.Ini_GetInt(RESCONFIGS_JOYSETTING, RESCONFIGN_DEBUG_JOYSPEEDUP, RESCONFIGDEFAULT_DEBUG_JOYSPEEDUP);
	end

	self.bgmvol			= hge.Ini_GetInt(RESCONFIGS_VOLUME, RESCONFIGN_VOLMUSIC, RESCONFIGDEFAULT_VOLMUSIC);
	self.sevol			= hge.Ini_GetInt(RESCONFIGS_VOLUME, RESCONFIGN_VOLSE, RESCONFIGDEFAULT_VOLSE);

	self.screenmode	= hge.Ini_GetInt(RESCONFIGS_CUSTOM, RESCONFIGN_SCREENMODE, RESCONFIGDEFAULT_SCREENMODE);
	self.username		= hge.Ini_GetString(RESCONFIGS_CUSTOM, RESCONFIGN_USERNAME, RESCONFIGDEFAULT_USERNAME);
	self.renderskip	= hge.Ini_GetInt(RESCONFIGS_CUSTOM, RESCONFIGN_RENDERSKIP, RESCONFIGDEFAULT_RENDERSKIP);

	if self.keyUp < 0 or self.keyUp >= M_KEYKEYMAX or
		self.keyDown < 0 or self.keyDown >= M_KEYKEYMAX or
		self.keyLeft < 0 or self.keyLeft >= M_KEYKEYMAX or
		self.keyRight < 0 or self.keyRight >= M_KEYKEYMAX or
		self.keyPause < 0 or self.keyPause >= M_KEYKEYMAX or
		self.keySkip < 0 or self.keySkip >= M_KEYKEYMAX or
		self.keyEnter < 0 or self.keyEnter >= M_KEYKEYMAX or
		self.keyCancel < 0 or self.keyCancel >= M_KEYKEYMAX or
		self.keyEscape < 0 or self.keyEscape >= M_KEYKEYMAX or
		self.keyCapture < 0 or self.keyCapture >= M_KEYKEYMAX or
		self.joyPause < 0 or self.joyPause >= M_JOYKEYMAX or
		self.bgmvol < 0 or self.bgmvol > 100 or
		self.sevol < 0 or self.sevol > 100 or
		self.renderskip < 0 or self.renderskip > 3 then
		self:_IniFileRebuild();
		return self:ProcessPreInitial();
	end
	if __DEBUG > 0 then
		if self.debug_joySpeedUp < 0 or self.debug_joySpeedUp > M_JOYKEYMAX then
			self:_IniFileRebuild();
			return self:ProcessPreInitial();
		end
	end
	if self.renderskip == 0 then
		self.renderskip = 1;
	end
	hge.System_SetState(HGE_RENDERSKIP, self.renderskip);
	
	if hge.Resource_AttachPack(RESLOADING_PCK, export:GetPassword()) then
		self.texInit = hge.Texture_Load(RESLOADING_TEX);
	else
		self.texInit = NULL;
	end
	return PGO;
end