#ifndef _LUACONSTDEFINE_H
#define _LUACONSTDEFINE_H

enum {
	LUAERROR_LOADINGSCRIPT
};

#define LUACALCULATESTR_INT			'i'
#define LUACALCULATESTR_DWORD		'd'
#define LUACALCULATESTR_LONGLONG	'l'
#define LUACALCULATESTR_QWORD		'q'

#endif