RESCONFIGS_SYSTEM	=	"System";
	RESCONFIGN_USE3DMODE				=	"Use3DMode";
	RESCONFIGDEFAULT_USE3DMODE	=	0;


RESCONFIGS_KEYSETTING	=	"KeySetting";
	RESCONFIGN_KEYUP						=	"KeyUp";
	RESCONFIGDEFAULT_KEYUP			=	DIK_UP;
	RESCONFIGN_KEYDOWN					=	"KeyDown";
	RESCONFIGDEFAULT_KEYDOWN		=	DIK_DOWN;
	RESCONFIGN_KEYLEFT					=	"KeyLeft";
	RESCONFIGDEFAULT_KEYLEFT		=	DIK_LEFT;
	RESCONFIGN_KEYRIGHT					=	"KeyRight";
	RESCONFIGDEFAULT_KEYRIGHT		=	DIK_RIGHT;
	RESCONFIGN_KEYPAUSE					=	"KeyPause";
	RESCONFIGDEFAULT_KEYPAUSE		=	DIK_SPACE;
	RESCONFIGN_KEYSKIP					=	"KeySkip";
	RESCONFIGDEFAULT_KEYSKIP		=	DIK_LCONTROL;
	RESCONFIGN_KEYENTER					=	"KeyEnter";
	RESCONFIGDEFAULT_KEYENTER		=	DIK_RETURN;
	RESCONFIGN_KEYESCAPE				=	"KeyEscape";
	RESCONFIGDEFAULT_KEYESCAPE	=	DIK_F4;
	RESCONFIGN_KEYCAPTURE				=	"KeyCapture";
	RESCONFIGDEFAULT_KEYCAPTURE	=	DIK_HOME;
	
RESCONFIGS_JOYSETTING	=	"JoySetting";
	RESCONFIGN_JOYPAUSE					="JoyPause";
	RESCONFIGDEFAULT_JOYPAUSE		=	1;

PQUIT		=	0;
PGO			=	1;
POK			=	2;
PBACK		=	3;
PTURN		=	4;
PSKIP		=	5;
PTITLE	=	6;


STATE_START							=	0;
STATE_PAUSE							=	1;
STATE_CONTINUE					=	2;
STATE_CLEAR							=	3;
STATE_ENDING						=	4;
STATE_TITLE							=	5;
STATE_OVER							=	6;
STATE_REPLAY						=	7;
STATE_RESULT						=	8;
STATE_OPTION						=	9;
STATE_MUSIC							=	10;
STATE_INIT							=	11;