__DEBUG	=	1

TITLE_STR	=	"LuaEngine";

CONFIG_STR_FILENAME	=	"LuaEngine.ini";

M_CLIENT_LEFT			=	0.0;
M_CLIENT_RIGHT		=	640.0;
M_CLIENT_TOP			=	0.0;
M_CLIENT_BOTTOM		=	480.0;
M_CLIENT_WIDTH		=	(M_CLIENT_RIGHT-M_CLIENT_LEFT);
M_CLIENT_HEIGHT		=	(M_CLIENT_BOTTOM-M_CLIENT_TOP);
M_CLIENT_CENTER_X	=	((M_CLIENT_LEFT+M_CLIENT_RIGHT)/2.0);
M_CLIENT_CENTER_Y	=	((M_CLIENT_TOP+M_CLIENT_BOTTOM)/2.0);

RESCONFIGS_SYSTEM	=	"System";
	RESCONFIGN_USE3DMODE				=	"Use3DMode";
	RESCONFIGDEFAULT_USE3DMODE	=	0;

RESCONFIGS_KEYSETTING	=	"KeySetting";
	RESCONFIGN_KEYUP						=	"KeyUp";
	RESCONFIGDEFAULT_KEYUP			=	DIK_UP;
	RESCONFIGN_KEYDOWN					=	"KeyDown";
	RESCONFIGDEFAULT_KEYDOWN		=	DIK_DOWN;
	RESCONFIGN_KEYLEFT					=	"KeyLeft";
	RESCONFIGDEFAULT_KEYLEFT		=	DIK_LEFT;
	RESCONFIGN_KEYRIGHT					=	"KeyRight";
	RESCONFIGDEFAULT_KEYRIGHT		=	DIK_RIGHT;
	RESCONFIGN_KEYPAUSE					=	"KeyPause";
	RESCONFIGDEFAULT_KEYPAUSE		=	DIK_SPACE;
	RESCONFIGN_KEYSKIP					=	"KeySkip";
	RESCONFIGDEFAULT_KEYSKIP		=	DIK_LCONTROL;
	RESCONFIGN_KEYENTER					=	"KeyEnter";
	RESCONFIGDEFAULT_KEYENTER		=	DIK_RETURN;
	RESCONFIGN_KEYESCAPE				=	"KeyEscape";
	RESCONFIGDEFAULT_KEYESCAPE	=	DIK_F4;
	RESCONFIGN_KEYCAPTURE				=	"KeyCapture";
	RESCONFIGDEFAULT_KEYCAPTURE	=	DIK_HOME;
	
RESCONFIGS_JOYSETTING	=	"JoySetting";
	RESCONFIGN_JOYPAUSE					="JoyPause";
	RESCONFIGDEFAULT_JOYPAUSE		=	1;
	if __DEBUG > 0 then
		RESCONFIGN_DEBUG_JOYSPEEDUP				=	"Debug_JoySpeedUp";
		RESCONFIGDEFAULT_DEBUG_JOYSPEEDUP	=	5;
	end

RESCONFIGS_VOLUME		=	"Volume";
	RESCONFIGN_VOLMUSIC				=	"Music";
	RESCONFIGDEFAULT_VOLMUSIC	=	100;
	RESCONFIGN_VOLSE					=	"SE";
	RESCONFIGDEFAULT_VOLSE		=100;

RESCONFIGS_CUSTOM		=	"Custom";
	RESCONFIGN_SCREENMODE				=	"ScreenMode";
	RESCONFIGDEFAULT_SCREENMODE	=	0;
	RESCONFIGN_USERNAME					=	"UserName";
	RESCONFIGDEFAULT_USERNAME		=	"NoName";
	RESCONFIGN_RENDERSKIP				=	"RenderSkip";
	RESCONFIGDEFAULT_RENDERSKIP	=	0;

RESCONFIGS_CUSTOMWINDOW		=	"CustomWindow";
	RESCONFIGN_DEFAULTWINDOW				=	"DefaultWindow";
	RESCONFIGDEFAULT_DEFAULTWINDOW	=	1;
	RESCONFIGN_WINDOWLEFT						=	"WindowLeft";
	RESCONFIGDEFAULT_WINDOWLEFT			=	0;
	RESCONFIGN_WINDOWTOP						=	"WindowTop";
	RESCONFIGDEFAULT_WINDOWTOP			=	0;
	RESCONFIGN_WINDOWWIDTH					=	"WindowWidth";
	RESCONFIGDEFAULT_WINDOWWIDTH		=	640;
	RESCONFIGN_WINDOWHEIGHT					=	"WindowHeight";
	RESCONFIGDEFAULT_WINDOWHEIGHT		=	480;
	RESCONFIGN_WINDOWTOPMOST				=	"WindowTopMost";
	RESCONFIGDEFAULT_WINDOWTOPMOST	=	0;

RESCONFIGS_RESOURCE				=	"Resource"
	RESCONFIGN_PASSWORD				=	"Password"
	RESCONFIGDEFAULT_PASSWORD	=	"h5nc"

RESDEFAULT_DATAFOLDER			=	"Data/"
RESDEFAULT_TEXTUREDEFINE	=	"TextureDefine.table"

PQUIT		=	0;
PGO			=	1;
POK			=	2;
PBACK		=	3;
PTURN		=	4;
PSKIP		=	5;
PTITLE	=	6;


STATE_START							=	0;
STATE_PAUSE							=	1;
STATE_CONTINUE					=	2;
STATE_CLEAR							=	3;
STATE_ENDING						=	4;
STATE_TITLE							=	5;
STATE_OVER							=	6;
STATE_REPLAY						=	7;
STATE_RESULT						=	8;
STATE_OPTION						=	9;
STATE_MUSIC							=	10;
STATE_INIT							=	11;

M_KEYKEYMAX	=	0x100;
M_JOYKEYMAX	=	0x20;

RESLOADING_PCK	=	"Loading.pck";
RESLOADING_TEX	=	"Loading/Loading.tex";