RESCONFIGS_SYSTEM	=	"System";
	RESCONFIGN_USE3DMODE				=	"Use3DMode";
	RESCONFIGDEFAULT_USE3DMODE	=	0;


RESCONFIGS_KEYSETTING	=	"KeySetting";
	RESCONFIGN_KEYUP						=	"KeyUp";
	RESCONFIGDEFAULT_KEYUP			=	DIK_UP;
	RESCONFIGN_KEYDOWN					=	"KeyDown";
	RESCONFIGDEFAULT_KEYDOWN		=	DIK_DOWN;
	RESCONFIGN_KEYLEFT					=	"KeyLeft";
	RESCONFIGDEFAULT_KEYLEFT		=	DIK_LEFT;
	RESCONFIGN_KEYRIGHT					=	"KeyRight";
	RESCONFIGDEFAULT_KEYRIGHT		=	DIK_RIGHT;
	RESCONFIGN_KEYPAUSE					=	"KeyPause";
	RESCONFIGDEFAULT_KEYPAUSE		=	DIK_SPACE;
	RESCONFIGN_KEYSKIP					=	"KeySkip";
	RESCONFIGDEFAULT_KEYSKIP		=	DIK_LCONTROL;
	RESCONFIGN_KEYENTER					=	"KeyEnter";
	RESCONFIGDEFAULT_KEYENTER		=	DIK_RETURN;
	RESCONFIGN_KEYESCAPE				=	"KeyEscape";
	RESCONFIGDEFAULT_KEYESCAPE	=	DIK_F4;
	RESCONFIGN_KEYCAPTURE				=	"KeyCapture";
	RESCONFIGDEFAULT_KEYCAPTURE	=	DIK_HOME;